ktor:
  deployment:
    # Optional PORT for Railway
    port: "$PORT:8080"
    environment: "$ENV:dev"
    watch: [ classes, resources ]

  application:
    modules: [ mjuzik.le.ApplicationKt.module ]

environments:
  dev:
    datasource:
      driver: "org.h2.Driver"
      url: "jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
      user: "sa"
      password: ""

  prod:
    datasource:
      driver: "org.postgresql.Driver"
      url: "$DATABASE_URL:jdbc:postgresql://localhost:5432/postgres"
      user: "$PGUSER:postgres"
      password: "$PGPASSWORD:postgres"
